// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/MessageManager.tsx": () => import("../components/mockups/MessageManager.tsx"),
  "./components/mockups/NotificationBellDropdown.tsx": () => import("../components/mockups/NotificationBellDropdown.tsx")
};
